version: '3'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5433:5432
    volumes:
      - aiotodo-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aiotodo
      - POSTGRES_PASSWORD=aiotodo

volumes:
  aiotodo-db: